@startuml
hide footbox
skinparam roundcorner 20
skinparam handwritten true
skinparam backgroundcolor transparent

skinparam note {
  FontName Impact
}


object Note {
    String : comment
    Person : author
    Date : createdOn
}

object Person {
    String : name
    String : email
}


Person --{ Note : has
@enduml
